CREATE TABLE IF NOT EXISTS USERS
(
    ID SERIAL PRIMARY KEY,
    LDAP VARCHAR(32) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(32) NOT NULL,
    LAST_NAME VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    ROLE VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS ARCHIVE
(
    ID VARCHAR(32) PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(32) NOT NULL,
    EXECUTOR VARCHAR(32),
    AUTHOR VARCHAR(256) NOT NULL,
    STATUS VARCHAR(32) NOT NULL
);

INSERT INTO USERS(LDAP, FIRST_NAME, LAST_NAME, PASSWORD, ROLE) VALUES ('admin', 'admin', 'admin', '$2a$10$3N2scUic8DXRigfjZRkHQ.GYkzLFsNXGHKJz2rNlxs6HpRxyyw2Ny', 'ROLE_CONTROL');

