DROP DATABASE activiti;

CREATE DATABASE activiti;

CREATE TABLE IF NOT EXISTS USERS
(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LDAP VARCHAR(32) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(32) NOT NULL,
    LAST_NAME VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS ARCHIVE
(
    ID VARCHAR(32) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    EXECUTOR VARCHAR(255),
    AUTHOR VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMMENTS
(
    ID SERIAL PRIMARY KEY,
    TASK_ID VARCHAR(32) NOT NULL,
    LDAP VARCHAR(32) NOT NULL,
    TEXT VARCHAR(255) NOT NULL,
    DATE TIMESTAMP NOT NULL
);

INSERT INTO USERS(LDAP, FIRST_NAME, LAST_NAME, PASSWORD, ROLE) VALUES ('admin', 'admin', 'admin', '$2a$10$3N2scUic8DXRigfjZRkHQ.GYkzLFsNXGHKJz2rNlxs6HpRxyyw2Ny', 'ROLE_CONTROL');

